# Generated by Django 5.1.3 on 2024-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pass_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_pass_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
