# Generated by Django 5.1.3 on 2025-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reset_pass_expire_date_user_reset_pass_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_user'),
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='certificates',
            field=models.FileField(blank=True, upload_to='image_certificates'),
        ),
    ]
